export const INDUSTRIES = [
  "Software / Technology",
  "FinTech",
  "HealthTech",
  "EdTech",
  "E-commerce",
  "SaaS",
  "Consulting",
  "Banking & Financial Services",
  "Insurance",
  "Telecommunications",
  "Media & Entertainment",
  "Gaming",
  "Manufacturing",
  "Automotive",
  "Retail",
  "Logistics & Supply Chain",
  "Energy & Utilities",
  "Real Estate",
  "Hospitality & Travel",
  "Healthcare",
  "Pharmaceuticals",
  "Education",
  "Government / Public Sector",
  "Non-profit",
  "Marketing & Advertising",
  "Human Resources",
  "Legal",
  "Cybersecurity",
  "Data & Analytics",
  "Cloud / Infrastructure",
  "AI / Machine Learning",
  "Other",
] as const;

export const JOB_TITLES = [
  "Software Engineer",
  "Senior Software Engineer",
  "Frontend Engineer",
  "Backend Engineer",
  "Full Stack Engineer",
  "QA Engineer",
  "QA Automation Engineer",
  "SDET",
  "Test Engineer",
  "DevOps Engineer",
  "Site Reliability Engineer",
  "Cloud Engineer",
  "Data Engineer",
  "Data Scientist",
  "Data Analyst",
  "Machine Learning Engineer",
  "AI Engineer",
  "Product Manager",
  "Technical Product Manager",
  "Project Manager",
  "Program Manager",
  "Engineering Manager",
  "Tech Lead",
  "Architect",
  "Solutions Architect",
  "UX Designer",
  "UI Designer",
  "Product Designer",
  "Business Analyst",
  "Scrum Master",
  "Customer Success Manager",
  "Account Manager",
  "Sales Engineer",
  "Recruiter",
  "HR Business Partner",
  "Marketing Manager",
  "Content Writer",
  "Support Engineer",
  "Security Engineer",
  "Mobile Developer",
  "iOS Developer",
  "Android Developer",
  "Other",
] as const;

export const SKILLS = [
  // Languages
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C#",
  "Go",
  "Rust",
  "Kotlin",
  "Swift",
  "PHP",
  "Ruby",
  "SQL",
  "R",
  "Scala",
  // Frontend
  "React",
  "Next.js",
  "Vue.js",
  "Angular",
  "HTML",
  "CSS",
  "Tailwind CSS",
  "Redux",
  // Backend
  "Node.js",
  "Express",
  "NestJS",
  "Django",
  "Flask",
  "FastAPI",
  "Spring Boot",
  ".NET",
  "GraphQL",
  "REST APIs",
  // Testing
  "Playwright",
  "Cypress",
  "Selenium",
  "Jest",
  "Pytest",
  "API Testing",
  "Automation Testing",
  "Manual Testing",
  "Performance Testing",
  "Appium",
  // Data / Cloud
  "AWS",
  "Azure",
  "GCP",
  "Docker",
  "Kubernetes",
  "Terraform",
  "CI/CD",
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "Redis",
  "Kafka",
  "Spark",
  "Airflow",
  "Snowflake",
  "Tableau",
  "Power BI",
  // Product / Design / Soft
  "Figma",
  "Product Strategy",
  "Agile / Scrum",
  "Stakeholder Management",
  "System Design",
  "Microservices",
  "Linux",
  "Git",
] as const;

export const LOOKING_FOR = [
  "Full-time employment",
  "Remote opportunities",
  "Hybrid roles",
  "Contract / freelance",
  "Part-time roles",
  "Startup opportunities",
  "Co-founder roles",
  "Side projects",
  "Open-source collaboration",
  "Mentorship",
  "Referrals",
  "Interview practice",
  "Career advice",
  "Leadership roles",
  "Individual contributor roles",
  "QA / SDET roles",
  "Engineering roles",
  "Product roles",
  "Design roles",
  "Data roles",
  "Management roles",
] as const;

export const COUNTRIES = [
  "India",
  "United States",
  "United Kingdom",
  "Canada",
  "Germany",
  "Australia",
  "Singapore",
  "United Arab Emirates",
  "Netherlands",
  "Ireland",
  "France",
  "Sweden",
  "Poland",
  "Brazil",
  "Mexico",
  "Japan",
  "South Korea",
  "New Zealand",
  "South Africa",
  "Other",
] as const;

export const PREFERRED_LOCATIONS = [
  "Remote",
  "Anywhere",
  "Bangalore",
  "Hyderabad",
  "Pune",
  "Mumbai",
  "Delhi NCR",
  "Chennai",
  "Jaipur",
  "Kolkata",
  "Ahmedabad",
  "San Francisco Bay Area",
  "New York",
  "Austin",
  "Seattle",
  "London",
  "Berlin",
  "Toronto",
  "Singapore",
  "Dubai",
] as const;

export const MAJOR_CITIES = [
  "Jaipur",
  "Bangalore",
  "Hyderabad",
  "Pune",
  "Mumbai",
  "Delhi",
  "Noida",
  "Gurgaon",
  "Chennai",
  "Kolkata",
  "Ahmedabad",
  "Chandigarh",
  "Kochi",
  "Indore",
  "Remote",
  "San Francisco",
  "New York",
  "Austin",
  "Seattle",
  "Chicago",
  "Boston",
  "London",
  "Manchester",
  "Berlin",
  "Amsterdam",
  "Toronto",
  "Vancouver",
  "Singapore",
  "Dubai",
  "Sydney",
  "Other",
] as const;
